#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 16 21:18:32 2018

@author: divkhare
"""
import math
def prime():
    primelist=[2,] 
    k=3
    n=10000
    while (k<=n):
        for number in primelist:
                    if (number > math.sqrt(k)): 
                        primelist.append(k) #number is prime and added to list 
                        break
                    elif (k%number==0) :
                        break
        k+=1 
    return primelist
pr = prime() #primelist stored in pr 
print(pr) #prints primelist
